#
# use: mingw_0703.yml
# use: hb32_0703.yml

name: hb32pack

on:
  push:
  schedule:
   - cron: "45 5 2 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'hb32pack'
        default: 'hb32pack'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: mingw 7.3
      uses: dawidd6/action-download-artifact@v2
      with:
         workflow: mingw_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/sefazclass

    - name: harbour 3.2
      uses: dawidd6/action-download-artifact@v2
      with:
         workflow: hb32_0703.yml
         workflow_conclusion: success
         name: hb32_0703
         path: c:\temp
         repo: JoseQuintas/sefazclass

    - name: Unzip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         7z x -y c:\temp\hb32_0703.7z -oc:\temp\harbour
         7z x -y c:\temp\mingw_0703.7z -oc:\temp\mingw

    - name: Load Source Code
      env:
         REPO_SEFAZ:   https://github.com/JoseQuintas/sefazclass
         REPO_HWGUI:   https://github.com/JoseQuintas/hwgui
         REPO_HMGE:    https://github.com/JoseQuintas/hmge
         PATH_HWGUI:   c:\temp\harbour\addons\hwgui
         PATH_HMGE:    c:\temp\harbour\addons\hmge
         PATH_SEFAZ:   c:\temp\harbour\addons\sefazclass
      run: |
         c:
         git clone $env:REPO_HWGUI  $env:PATH_HWGUI  --depth 1
         git clone $env:REPO_HMGE   $env:PATH_HMGE   --depth 1
         git clone $env:REPO_SEFAZ  $env:PATH_SEFAZ  --depth 1

    - name: Build All
      env:
         HB_BUILD_STRIP: all
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         HBMK_CMD: -workdir=c:\temp -q -quiet
         PATH: c:\temp\mingw\mingw32\bin;c:\temp\harbour\bin
      run: |
         c:
         #copy c:\temp\harbour\sefazclass\gtwvg.hbc c:\temp\harbour\contrib\gtwvg

         cd c:\temp\harbour\addons\sefazclass\sefazclass
         hbmk2 sefazclass.hbp

         cd c:\temp\harbour\addons\sefazclass\bostaurus
         hbmk2 bostaurus.hbp

         cd c:\temp\harbour\addons\sefazclass\rmchartclass
         hbmk2 rmchartclass.hbp

         cd c:\temp\harbour\addons\sefazclass\pdfclass
         hbmk2 pdfclass.hbp

         cd c:\temp\harbour\addons\sefazclass\wvgtest
         hbmk2 wvgtest.hbp -q

         cd c:\temp\harbour\addons\hwgui
         hbmk2 hwgui.hbp -q

         cd c:\temp\harbour\addons\hmge
         hbmk2 hmge.hbp -q

         #cd c:\temp\harbour\addons\hmg3
         #hbmk2 hmg3.hbp -workdir=c:\temp -quiet -q

    - name: Zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         7z a -r c:\temp\hb34pack.7z c:\temp\harbour\*.* -xr'!.git' -xr'!.github' -xr'!.hbmk'

#    - name: upload
#      uses: actions/upload-artifact@v2
#      with:
#         name: assets-for-download
#         path: c:\temp\harbour

    - name: Save
      uses: actions/upload-artifact@v3
      with:
         name: harbour
         path: c:\temp\hb34pack.7z

